version: '3.9'
services:
  agent:
    build: .
    privileged: true
    ports:
      - "8080:80"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ./captures:/captures
      - ./logs:/var/log/enigma-agent
    command: /entrypoint.sh

  loadtest:
    image: loadimpact/loadgentest-hey
    depends_on:
      - agent
    entrypoint: ["sh", "-c", "hey -n 10000 -q 100 http://agent"]
