name: Build Release Binaries

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build binaries for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go-version: ['1.24.x']

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
          cache: true

      - name: Build binary
        run: |
          mkdir -p bin
          if [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
            GOOS=linux GOARCH=amd64 go build -o bin/enigma-agent-linux-amd64 ./cmd/enigma-agent
          elif [ "${{ matrix.os }}" = "macos-latest" ]; then
            GOOS=darwin GOARCH=amd64 go build -o bin/enigma-agent-darwin-amd64 ./cmd/enigma-agent
          elif [ "${{ matrix.os }}" = "windows-latest" ]; then
            GOOS=windows GOARCH=amd64 go build -o bin/enigma-agent-windows-amd64.exe ./cmd/enigma-agent
          fi
        shell: bash

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: enigma-agent-${{ matrix.os }}
          path: |
            bin/enigma-agent-*