name: Build Release Binaries

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build binaries for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go-version: ['1.24.x']

    steps:
      - uses: actions/checkout@v4

      - name: Extract version from tag
        id: get_version
        run: echo "version=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
          cache: true

      - name: Build binary
        run: |
          mkdir -p bin
          VERSION=${{ steps.get_version.outputs.version }}
          if [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
            GOOS=linux GOARCH=amd64 go build -o bin/enigma-agent-linux-amd64-${VERSION} ./cmd/enigma-agent
          elif [ "${{ matrix.os }}" = "macos-latest" ]; then
            GOOS=darwin GOARCH=amd64 go build -o bin/enigma-agent-darwin-amd64-${VERSION} ./cmd/enigma-agent
          elif [ "${{ matrix.os }}" = "windows-latest" ]; then
            GOOS=windows GOARCH=amd64 go build -o bin/enigma-agent-windows-amd64-${VERSION}.exe ./cmd/enigma-agent
          fi
        shell: bash

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: enigma-agent-${{ matrix.os }}-${{ steps.get_version.outputs.version }}
          path: |
            bin/enigma-agent-*-${{ steps.get_version.outputs.version }}*

      - name: Upload binaries to GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: bin/enigma-agent-*-${{ steps.get_version.outputs.version }}*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}